### ISSUE TITLE
Update URIs to w3id

### ISSUE THREAD

**Issue by ricklupton** [probs-lab/probs-runner#3]
`https://w3id.org/probs-lab/ontology/`

**Comment by stefanogermano** [comment]
I am not sure why we need to hardcode this value in the Python code.
Although I expect it will not change again, I think that is a bad practice.

We could use the prefix whenever possible (or the base IRI).
When that is not possible, we can retrieve the IRI from RDFox (for instance, using the `base` or `prefixes` commands, or even with a SPARQL query).

@ricklupton is there a specific reason why we want to hardcode it?

**Comment by ricklupton** [comment]
We provide it [here](https://github.com/probs-lab/probs-runner/blob/2d533591398128fe5b48f5ae64c9f0e405ed2aad/src/probs_runner/namespace.py#L5) as a convenience for working with RDF or queries from Python.

As far as I know, if you submit a query to the RDFox endpoint, it is "standalone" and needs to have any prefixes you want to use defined within each query. Like in our [test queries](https://github.com/probs-lab/ukfires-probs-docs/blob/v2/Ontologies/scripts/test-queries/queries/query18.rq)

So, if we don't hard-code this once here, won't it get hard-coded many more times in every place that a query is run from Python, which is probably worse?

**Comment by stefanogermano** [comment]
> As far as I know, if you submit a query to the RDFox endpoint, it is "standalone" and needs to have any prefixes you want to use defined within each query. Like in our [test queries](https://github.com/probs-lab/ukfires-probs-docs/blob/v2/Ontologies/scripts/test-queries/queries/query18.rq)

Actually, that was true in older versions of RDFox, but it is not true anymore.
Those prefixes in the files with the queries are no longer needed (I do not know why we have not removed yet, but now is probably too late since we are going to remove all the queries when we remove the loading/mapping https://github.com/probs-lab/ukfires-probs-docs/issues/397).
Moreover, even if you ask the query 'directly' (i.e., without storing it into a file), you do not need prefixes (in the query statement).

In any case, instead of hardcoding it in the code, we could compute it at the beginning, store it somewhere (in a variable), and use it whenever we need.

**Comment by ricklupton** [comment]
Done in 40adf5254375f4517cc1688db2b730f407b9aa33

I think it's useful to have it here so that anyone using probs-runner to work with RDF from Python has the appropriate namespace/prefix, without needing a running copy of RDFox.
